server:
  port: 8080




spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #连接池
    url: jdbc:mysql://localhost:3306/wsblog?useUnicode=true&characterEncoding=utf8 #连接地址
    username: root #用户名
    password: 123456 #密码
  jackson:
    date-format: yyyy-MM-dd #时间格式转换
    time-zone: GMT+8 #时区规定
  profiles:
    active: dev
  mail:
    host: smtp.qq.com
    username: 1924837954@qq.com
    password: ybuurusnyhiueidh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    default-encoding: utf-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB



#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    serialization: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5 #加密密钥
    expire: 604800 #有效时长
    header: Authorization
shiro-redis:
  enbled: true
  redis-manager:
    host: 127.0.0.1:6379



